name: Shopify Continuous Integration Workflow

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1
            -   name: Ballerina Build
                uses: ballerina-platform/ballerina-action@master
                with:
                    args:
                        build -a -c
                env:
                    shopify_token: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
